import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useApi from "../lib/use-api"
import { useState } from 'react'

export default function Home() {
  const [url, setUrl] = useState("/api/users")
  const { response: users, error, isLoading } = useApi(url)

  return (
    <div className={styles.container}>
      <Head>
        <title>CipherStash Next Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://cipherstash.com">CipherStash</a>
          <br/>
          Next.js Demo
        </h1>

        <input
          type="text"
          placeholder="Search users..."
          onChange={(elem) => {
            setUrl("/api/users?q="+elem.target.value)
          }}
        />
        <div>
          {isLoading && <p>Loading users...</p>}

          {users && (
            <>
              <table>
                <tbody>
                  {users.map(user => (
                    <tr key={user.id}>
                      <td>{ user.name }</td>
                      <td>{ user.email }</td>
                      <td>{ user.phone }</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </>
          )}

          {error && (
            <>
              <pre>
                <code>{JSON.stringify(error, null, 2)}</code>
              </pre>
            </>
          )}
        </div>
      </main>
      <footer className={styles.footer}>
        <p>
          Check out the CipherStash <a href="https://docs.cipherstash.com">docs</a> for more information.
        </p>
      </footer>
    </div>
  )
}
